name: Deploy to Server

on:
  push:
    branches: [ main ] # main 브랜치에 직접 푸시하거나 PR이 merge될 때 실행
  pull_request:
    types: [closed]
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # PR이 merge된 경우에만 실행 (직접 push거나 PR이 merge된 경우)
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
      - uses: actions/checkout@v3
      
      - name: Deploy with expect
        env:
          SERVER_PASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          sudo apt-get update
          sudo apt-get install -y expect
          
          # NVM 설치 및 Node.js 설정
          cat > setup_node.exp << 'EOL'
          #!/usr/bin/expect -f
          spawn ssh -o StrictHostKeyChecking=no defectect@166.104.246.64 "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash && export NVM_DIR=\$HOME/.nvm && . \$NVM_DIR/nvm.sh && nvm install 18 && nvm use 18"
          expect "password:"
          send "$env(SERVER_PASS)\r"
          expect eof
          EOL
          chmod +x setup_node.exp
          ./setup_node.exp
          
          # 프로젝트 클론 및 빌드
          cat > build_on_server.exp << 'EOL'
          #!/usr/bin/expect -f
          spawn ssh -o StrictHostKeyChecking=no defectect@166.104.246.64 "mkdir -p ~/website && cd ~/website && git clone https://github.com/HYCapstoneProject-NEXED/client.git . || git pull && export NVM_DIR=\$HOME/.nvm && . \$NVM_DIR/nvm.sh && nvm use 18 && npm ci && CI=false npm run build"
          expect "password:"
          send "$env(SERVER_PASS)\r"
          expect eof
          EOL
          chmod +x build_on_server.exp
          ./build_on_server.exp
          
          # 서버 실행
          cat > run_server.exp << 'EOL'
          #!/usr/bin/expect -f
          spawn ssh -o StrictHostKeyChecking=no defectect@166.104.246.64 "cd ~/website && export NVM_DIR=\$HOME/.nvm && . \$NVM_DIR/nvm.sh && nvm use 18 && npm install -g serve && pkill -f \"serve -s build\" || true && nohup serve -s build -l 3000 > server.log 2>&1 & echo \$! > serve.pid"
          expect "password:"
          send "$env(SERVER_PASS)\r"
          expect eof
          EOL
          chmod +x run_server.exp
          ./run_server.exp 