name: Deploy to Server

on:
  push:
    branches: [ main ] # main 브랜치에 직접 푸시하거나 PR이 merge될 때 실행
  pull_request:
    types: [closed]
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # PR이 merge된 경우에만 실행 (직접 push거나 PR이 merge된 경우)
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: CI=false npm run build
      
      - name: Deploy using sshpass
        uses: appleboy/scp-action@master
        with:
          host: 166.104.246.64
          username: defectect
          password: defectect!!@
          source: "build/,Dockerfile.production,docker-compose.production.yml,nginx.conf"
          target: "website"
          
      - name: Start Docker containers
        uses: appleboy/ssh-action@master
        with:
          host: 166.104.246.64
          username: defectect
          password: defectect!!@
          script: |
            cd ~/website
            cp docker-compose.production.yml docker-compose.yml
            docker-compose up -d --build 